import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const jejuHallasan = localFont({ src: '../public/fonts/JejuHallasan.woff2'})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jejuHallasan.className}>
        {children}
      </body>
    </html>
  );
}
